package mcperr_test

import (
	"testing"

	"pgregory.net/rapid"

	"github.com/vandrushkevich/pulse/mcp/internal/mcperr"
	"github.com/vandrushkevich/pulse/mcp/internal/pulseapi"
)

// Feature: mcp-server, Property 28: Pulse error envelope is preserved verbatim with request id
//
// For any PulseError with non-empty Code, Message, and RequestID fields,
// FromPulseError preserves ALL three fields verbatim in the MCPError result
// (unless HTTP 401 where code becomes PULSE_UNAUTHORIZED but message and
// RequestID are still preserved).
//
// **Validates: Requirements 9.4, 12.1, 12.3**
func TestProperty28_PulseErrorEnvelopePreservedVerbatim(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		code := rapid.StringMatching(`[A-Z][A-Z0-9_]{1,30}`).Draw(t, "code")
		message := rapid.StringMatching(`.{1,200}`).Draw(t, "message")
		requestID := rapid.StringMatching(`req-[a-z0-9]{4,20}`).Draw(t, "requestID")

		// Generate HTTP status: any non-401 status in the error range (400-599 excluding 401)
		httpStatus := rapid.OneOf(
			rapid.IntRange(400, 400),
			rapid.IntRange(402, 599),
		).Draw(t, "httpStatus")

		pe := &pulseapi.PulseError{
			Code:       code,
			Message:    message,
			RequestID:  requestID,
			HTTPStatus: httpStatus,
		}

		got := mcperr.FromPulseError(pe)

		// Non-401: code, message, and requestID are preserved verbatim
		if got.Code != code {
			t.Fatalf("Code not preserved: got %q, want %q", got.Code, code)
		}
		if got.Message != message {
			t.Fatalf("Message not preserved: got %q, want %q", got.Message, message)
		}
		if got.RequestID != requestID {
			t.Fatalf("RequestID not preserved: got %q, want %q", got.RequestID, requestID)
		}
	})

	// Sub-property: HTTP 401 maps code to PULSE_UNAUTHORIZED but preserves message and requestID
	rapid.Check(t, func(t *rapid.T) {
		code := rapid.StringMatching(`[A-Z][A-Z0-9_]{1,30}`).Draw(t, "code")
		message := rapid.StringMatching(`.{1,200}`).Draw(t, "message")
		requestID := rapid.StringMatching(`req-[a-z0-9]{4,20}`).Draw(t, "requestID")

		pe := &pulseapi.PulseError{
			Code:       code,
			Message:    message,
			RequestID:  requestID,
			HTTPStatus: 401,
		}

		got := mcperr.FromPulseError(pe)

		if got.Code != mcperr.CodePulseUnauthorized {
			t.Fatalf("401 should map to PULSE_UNAUTHORIZED, got %q", got.Code)
		}
		if got.Message != message {
			t.Fatalf("Message not preserved on 401: got %q, want %q", got.Message, message)
		}
		if got.RequestID != requestID {
			t.Fatalf("RequestID not preserved on 401: got %q, want %q", got.RequestID, requestID)
		}
	})
}

// Feature: mcp-server, Property 29: Connectivity/timeout failures map to a distinct error
//
// For any ConnectivityError, FromConnectivityError returns an MCPError whose code
// is PULSE_TIMEOUT when reason is "timeout", and PULSE_UNREACHABLE otherwise.
// Both codes are distinct from any PulseError code that could be preserved.
//
// **Validates: Requirements 1.7, 2.4, 12.4**
func TestProperty29_ConnectivityFailuresMapToDistinctError(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		// Generate a reason: either "timeout" or an arbitrary non-timeout reason
		isTimeout := rapid.Bool().Draw(t, "isTimeout")
		var reason string
		if isTimeout {
			reason = "timeout"
		} else {
			// Any non-empty reason that is NOT "timeout"
			reason = rapid.OneOf(
				rapid.Just("connection_refused"),
				rapid.Just("dial_error"),
				rapid.Just("dns_resolution_failed"),
				rapid.Just("network_unreachable"),
				rapid.StringMatching(`[a-z_]{1,30}`).Filter(func(s string) bool {
					return s != "timeout"
				}),
			).Draw(t, "reason")
		}

		ce := &pulseapi.ConnectivityError{Reason: reason}
		got := mcperr.FromConnectivityError(ce)

		// Check correct code assignment
		if isTimeout {
			if got.Code != mcperr.CodePulseTimeout {
				t.Fatalf("timeout reason should produce PULSE_TIMEOUT, got %q", got.Code)
			}
		} else {
			if got.Code != mcperr.CodePulseUnreachable {
				t.Fatalf("non-timeout reason %q should produce PULSE_UNREACHABLE, got %q", reason, got.Code)
			}
		}

		// Distinctness: connectivity codes must never equal a Pulse-origin code.
		// A Pulse-origin code is any code that FromPulseError would preserve verbatim
		// (i.e., the PulseError.Code field). Since FromPulseError preserves arbitrary codes,
		// we verify that PULSE_TIMEOUT and PULSE_UNREACHABLE are reserved constants that
		// won't collide with codes generated by Pulse (which uses patterns like
		// MONITOR_NOT_FOUND, VALIDATION_ERROR, etc.).
		// The design guarantees distinctness by reserving the PULSE_ prefix for connectivity.
		if got.Code != mcperr.CodePulseTimeout && got.Code != mcperr.CodePulseUnreachable {
			t.Fatalf("connectivity error code should be one of the reserved codes, got %q", got.Code)
		}

		// Additionally verify that a PulseError with the SAME code as a connectivity code
		// would still be distinguishable at the source level (this tests design intent).
		// The connectivity codes are internal constants that Pulse API would never emit.
		pulseReservedCodes := []string{mcperr.CodePulseTimeout, mcperr.CodePulseUnreachable}
		for _, reserved := range pulseReservedCodes {
			// These codes are distinct by design - verify they're the expected constants
			if reserved != "PULSE_TIMEOUT" && reserved != "PULSE_UNREACHABLE" {
				t.Fatalf("reserved code constant changed unexpectedly: %q", reserved)
			}
		}
	})
}

// Feature: mcp-server, Property 30: Every MCP error carries a code and a message
//
// For ANY MCPError produced by any constructor (FromPulseError, FromConnectivityError,
// Validation, InvalidType, AmbiguousName, NotFound, InvalidRange, InvalidIdentifier,
// InvalidWindow, WriteDisabled), the Code is non-empty and the Message is non-empty.
//
// **Validates: Requirements 12.2**
func TestProperty30_EveryMCPErrorCarriesCodeAndMessage(t *testing.T) {
	// Sub-test: FromPulseError always produces non-empty code and message
	rapid.Check(t, func(t *rapid.T) {
		code := rapid.StringMatching(`[A-Z][A-Z0-9_]{1,30}`).Draw(t, "code")
		message := rapid.StringMatching(`.{1,200}`).Draw(t, "message")
		requestID := rapid.StringMatching(`[a-z0-9\-]{0,20}`).Draw(t, "requestID")
		httpStatus := rapid.IntRange(400, 599).Draw(t, "httpStatus")

		pe := &pulseapi.PulseError{
			Code:       code,
			Message:    message,
			RequestID:  requestID,
			HTTPStatus: httpStatus,
		}

		got := mcperr.FromPulseError(pe)
		if got.Code == "" {
			t.Fatal("FromPulseError produced empty Code")
		}
		if got.Message == "" {
			t.Fatal("FromPulseError produced empty Message")
		}
	})

	// Sub-test: FromConnectivityError always produces non-empty code and message
	rapid.Check(t, func(t *rapid.T) {
		reason := rapid.OneOf(
			rapid.Just("timeout"),
			rapid.Just("connection_refused"),
			rapid.Just("dial_error"),
			rapid.StringMatching(`[a-z_]{1,30}`),
		).Draw(t, "reason")

		ce := &pulseapi.ConnectivityError{Reason: reason}
		got := mcperr.FromConnectivityError(ce)
		if got.Code == "" {
			t.Fatal("FromConnectivityError produced empty Code")
		}
		if got.Message == "" {
			t.Fatal("FromConnectivityError produced empty Message")
		}
	})

	// Sub-test: All helper constructors produce non-empty code and message
	rapid.Check(t, func(t *rapid.T) {
		msg := rapid.StringMatching(`.{1,200}`).Draw(t, "msg")

		constructors := []*mcperr.MCPError{
			mcperr.Validation(msg),
			mcperr.InvalidType(msg),
			mcperr.AmbiguousName(msg),
			mcperr.NotFound(msg),
			mcperr.InvalidRange(msg),
			mcperr.InvalidIdentifier(msg),
			mcperr.InvalidWindow(msg),
			mcperr.WriteDisabled(),
		}

		for i, err := range constructors {
			if err.Code == "" {
				t.Fatalf("constructor %d produced empty Code", i)
			}
			if err.Message == "" {
				t.Fatalf("constructor %d produced empty Message", i)
			}
		}
	})
}
