// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO monitor_credentials (monitor_id, auth_type, name, encrypted_value)
VALUES ($1, $2, $3, $4)
RETURNING id, monitor_id, auth_type, name, created_at, updated_at
`

type CreateCredentialParams struct {
	MonitorID      uuid.UUID `db:"monitor_id" json:"monitor_id"`
	AuthType       string    `db:"auth_type" json:"auth_type"`
	Name           string    `db:"name" json:"name"`
	EncryptedValue string    `db:"encrypted_value" json:"encrypted_value"`
}

type CreateCredentialRow struct {
	ID        uuid.UUID `db:"id" json:"id"`
	MonitorID uuid.UUID `db:"monitor_id" json:"monitor_id"`
	AuthType  string    `db:"auth_type" json:"auth_type"`
	Name      string    `db:"name" json:"name"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (CreateCredentialRow, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.MonitorID,
		arg.AuthType,
		arg.Name,
		arg.EncryptedValue,
	)
	var i CreateCredentialRow
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.AuthType,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM monitor_credentials WHERE id = $1 AND monitor_id = $2
`

type DeleteCredentialParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	MonitorID uuid.UUID `db:"monitor_id" json:"monitor_id"`
}

func (q *Queries) DeleteCredential(ctx context.Context, arg DeleteCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteCredential, arg.ID, arg.MonitorID)
	return err
}

const getCredential = `-- name: GetCredential :one
SELECT id, monitor_id, auth_type, name, encrypted_value, created_at, updated_at
FROM monitor_credentials
WHERE id = $1 AND monitor_id = $2
`

type GetCredentialParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	MonitorID uuid.UUID `db:"monitor_id" json:"monitor_id"`
}

func (q *Queries) GetCredential(ctx context.Context, arg GetCredentialParams) (MonitorCredential, error) {
	row := q.db.QueryRow(ctx, getCredential, arg.ID, arg.MonitorID)
	var i MonitorCredential
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.AuthType,
		&i.Name,
		&i.EncryptedValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllCredentials = `-- name: ListAllCredentials :many
SELECT id, encrypted_value FROM monitor_credentials ORDER BY id
`

type ListAllCredentialsRow struct {
	ID             uuid.UUID `db:"id" json:"id"`
	EncryptedValue string    `db:"encrypted_value" json:"encrypted_value"`
}

// Used by key rotation
func (q *Queries) ListAllCredentials(ctx context.Context) ([]ListAllCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listAllCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllCredentialsRow{}
	for rows.Next() {
		var i ListAllCredentialsRow
		if err := rows.Scan(&i.ID, &i.EncryptedValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialsByMonitorID = `-- name: ListCredentialsByMonitorID :many
SELECT id, monitor_id, auth_type, name, encrypted_value, created_at, updated_at
FROM monitor_credentials
WHERE monitor_id = $1
ORDER BY created_at
`

func (q *Queries) ListCredentialsByMonitorID(ctx context.Context, monitorID uuid.UUID) ([]MonitorCredential, error) {
	rows, err := q.db.Query(ctx, listCredentialsByMonitorID, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitorCredential{}
	for rows.Next() {
		var i MonitorCredential
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.AuthType,
			&i.Name,
			&i.EncryptedValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialsByMonitorIDInternal = `-- name: ListCredentialsByMonitorIDInternal :many
SELECT id, auth_type, encrypted_value
FROM monitor_credentials
WHERE monitor_id = $1
`

type ListCredentialsByMonitorIDInternalRow struct {
	ID             uuid.UUID `db:"id" json:"id"`
	AuthType       string    `db:"auth_type" json:"auth_type"`
	EncryptedValue string    `db:"encrypted_value" json:"encrypted_value"`
}

// Used by scheduler to fetch encrypted values for injection
func (q *Queries) ListCredentialsByMonitorIDInternal(ctx context.Context, monitorID uuid.UUID) ([]ListCredentialsByMonitorIDInternalRow, error) {
	rows, err := q.db.Query(ctx, listCredentialsByMonitorIDInternal, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCredentialsByMonitorIDInternalRow{}
	for rows.Next() {
		var i ListCredentialsByMonitorIDInternalRow
		if err := rows.Scan(&i.ID, &i.AuthType, &i.EncryptedValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredential = `-- name: UpdateCredential :one
UPDATE monitor_credentials
SET name = $3, encrypted_value = $4, updated_at = now()
WHERE id = $1 AND monitor_id = $2
RETURNING id, monitor_id, auth_type, name, created_at, updated_at
`

type UpdateCredentialParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	MonitorID      uuid.UUID `db:"monitor_id" json:"monitor_id"`
	Name           string    `db:"name" json:"name"`
	EncryptedValue string    `db:"encrypted_value" json:"encrypted_value"`
}

type UpdateCredentialRow struct {
	ID        uuid.UUID `db:"id" json:"id"`
	MonitorID uuid.UUID `db:"monitor_id" json:"monitor_id"`
	AuthType  string    `db:"auth_type" json:"auth_type"`
	Name      string    `db:"name" json:"name"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) (UpdateCredentialRow, error) {
	row := q.db.QueryRow(ctx, updateCredential,
		arg.ID,
		arg.MonitorID,
		arg.Name,
		arg.EncryptedValue,
	)
	var i UpdateCredentialRow
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.AuthType,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCredentialEncryptedValue = `-- name: UpdateCredentialEncryptedValue :exec
UPDATE monitor_credentials SET encrypted_value = $2, updated_at = now() WHERE id = $1
`

type UpdateCredentialEncryptedValueParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	EncryptedValue string    `db:"encrypted_value" json:"encrypted_value"`
}

// Used by key rotation
func (q *Queries) UpdateCredentialEncryptedValue(ctx context.Context, arg UpdateCredentialEncryptedValueParams) error {
	_, err := q.db.Exec(ctx, updateCredentialEncryptedValue, arg.ID, arg.EncryptedValue)
	return err
}
