// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countIncidents = `-- name: CountIncidents :one
SELECT COUNT(*) FROM incidents
`

func (q *Queries) CountIncidents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countIncidents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIncidentsByMonitor = `-- name: CountIncidentsByMonitor :one
SELECT COUNT(*) FROM incidents WHERE monitor_id = $1
`

func (q *Queries) CountIncidentsByMonitor(ctx context.Context, monitorID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countIncidentsByMonitor, monitorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (monitor_id, started_at, cause)
VALUES ($1, $2, $3)
RETURNING id, monitor_id, started_at, resolved_at, cause, created_at
`

type CreateIncidentParams struct {
	MonitorID uuid.UUID `db:"monitor_id" json:"monitor_id"`
	StartedAt time.Time `db:"started_at" json:"started_at"`
	Cause     *string   `db:"cause" json:"cause"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident, arg.MonitorID, arg.StartedAt, arg.Cause)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Cause,
		&i.CreatedAt,
	)
	return i, err
}

const getIncident = `-- name: GetIncident :one
SELECT id, monitor_id, started_at, resolved_at, cause, created_at FROM incidents WHERE id = $1
`

func (q *Queries) GetIncident(ctx context.Context, id uuid.UUID) (Incident, error) {
	row := q.db.QueryRow(ctx, getIncident, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Cause,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenIncidentByMonitor = `-- name: GetOpenIncidentByMonitor :one
SELECT id, monitor_id, started_at, resolved_at, cause, created_at FROM incidents
WHERE monitor_id = $1
  AND resolved_at IS NULL
LIMIT 1
`

func (q *Queries) GetOpenIncidentByMonitor(ctx context.Context, monitorID uuid.UUID) (Incident, error) {
	row := q.db.QueryRow(ctx, getOpenIncidentByMonitor, monitorID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Cause,
		&i.CreatedAt,
	)
	return i, err
}

const listIncidents = `-- name: ListIncidents :many
SELECT id, monitor_id, started_at, resolved_at, cause, created_at FROM incidents
ORDER BY started_at DESC
LIMIT $1 OFFSET $2
`

type ListIncidentsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.Cause,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentsByMonitor = `-- name: ListIncidentsByMonitor :many
SELECT id, monitor_id, started_at, resolved_at, cause, created_at FROM incidents
WHERE monitor_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListIncidentsByMonitorParams struct {
	MonitorID uuid.UUID `db:"monitor_id" json:"monitor_id"`
	Limit     int32     `db:"limit" json:"limit"`
	Offset    int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListIncidentsByMonitor(ctx context.Context, arg ListIncidentsByMonitorParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidentsByMonitor, arg.MonitorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.Cause,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenIncidents = `-- name: ListOpenIncidents :many
SELECT id, monitor_id, started_at, resolved_at, cause, created_at FROM incidents
WHERE resolved_at IS NULL
ORDER BY started_at DESC
LIMIT $1 OFFSET $2
`

type ListOpenIncidentsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListOpenIncidents(ctx context.Context, arg ListOpenIncidentsParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listOpenIncidents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.Cause,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveIncident = `-- name: ResolveIncident :one
UPDATE incidents
SET resolved_at = $2
WHERE id = $1
RETURNING id, monitor_id, started_at, resolved_at, cause, created_at
`

type ResolveIncidentParams struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	ResolvedAt pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
}

func (q *Queries) ResolveIncident(ctx context.Context, arg ResolveIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, resolveIncident, arg.ID, arg.ResolvedAt)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Cause,
		&i.CreatedAt,
	)
	return i, err
}
