// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitors.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMonitors = `-- name: CountMonitors :one
SELECT COUNT(*) FROM monitors
`

func (q *Queries) CountMonitors(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMonitors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (
    name, type, target, interval_seconds, timeout_seconds,
    status, state, settings, next_check_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
RETURNING id, name, type, target, interval_seconds, timeout_seconds, status, state, last_checked_at, next_check_at, settings, created_at, updated_at
`

type CreateMonitorParams struct {
	Name            string             `db:"name" json:"name"`
	Type            string             `db:"type" json:"type"`
	Target          string             `db:"target" json:"target"`
	IntervalSeconds int32              `db:"interval_seconds" json:"interval_seconds"`
	TimeoutSeconds  int32              `db:"timeout_seconds" json:"timeout_seconds"`
	Status          string             `db:"status" json:"status"`
	State           string             `db:"state" json:"state"`
	Settings        json.RawMessage    `db:"settings" json:"settings"`
	NextCheckAt     pgtype.Timestamptz `db:"next_check_at" json:"next_check_at"`
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.Name,
		arg.Type,
		arg.Target,
		arg.IntervalSeconds,
		arg.TimeoutSeconds,
		arg.Status,
		arg.State,
		arg.Settings,
		arg.NextCheckAt,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Target,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.Status,
		&i.State,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMonitor = `-- name: DeleteMonitor :exec
DELETE FROM monitors WHERE id = $1
`

func (q *Queries) DeleteMonitor(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMonitor, id)
	return err
}

const getMonitor = `-- name: GetMonitor :one
SELECT id, name, type, target, interval_seconds, timeout_seconds, status, state, last_checked_at, next_check_at, settings, created_at, updated_at FROM monitors
WHERE id = $1
`

func (q *Queries) GetMonitor(ctx context.Context, id uuid.UUID) (Monitor, error) {
	row := q.db.QueryRow(ctx, getMonitor, id)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Target,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.Status,
		&i.State,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMonitorForUpdate = `-- name: GetMonitorForUpdate :one
SELECT id, name, type, target, interval_seconds, timeout_seconds, status, state, last_checked_at, next_check_at, settings, created_at, updated_at FROM monitors
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetMonitorForUpdate(ctx context.Context, id uuid.UUID) (Monitor, error) {
	row := q.db.QueryRow(ctx, getMonitorForUpdate, id)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Target,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.Status,
		&i.State,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveMonitorsDue = `-- name: ListActiveMonitorsDue :many
SELECT id, name, type, target, interval_seconds, timeout_seconds, status, state, last_checked_at, next_check_at, settings, created_at, updated_at FROM monitors
WHERE status = 'active'
  AND (next_check_at IS NULL OR next_check_at <= now())
ORDER BY next_check_at ASC NULLS FIRST
LIMIT $1
`

func (q *Queries) ListActiveMonitorsDue(ctx context.Context, limit int32) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listActiveMonitorsDue, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Target,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.Status,
			&i.State,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveMonitorsDueWithTags = `-- name: ListActiveMonitorsDueWithTags :many
SELECT m.id, m.name, m.type, m.target, m.interval_seconds, m.timeout_seconds,
       m.status, m.state, m.last_checked_at, m.next_check_at, m.settings,
       m.created_at, m.updated_at,
       COALESCE(
         json_agg(json_build_object('key', mt.key, 'value', mt.value))
         FILTER (WHERE mt.key IS NOT NULL),
         '[]'::json
       ) AS tags_json
FROM monitors m
LEFT JOIN monitor_tags mt ON mt.monitor_id = m.id
WHERE m.status = 'active'
  AND (m.next_check_at IS NULL OR m.next_check_at <= now())
GROUP BY m.id
ORDER BY m.next_check_at ASC NULLS FIRST
LIMIT $1
`

type ListActiveMonitorsDueWithTagsRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Name            string             `db:"name" json:"name"`
	Type            string             `db:"type" json:"type"`
	Target          string             `db:"target" json:"target"`
	IntervalSeconds int32              `db:"interval_seconds" json:"interval_seconds"`
	TimeoutSeconds  int32              `db:"timeout_seconds" json:"timeout_seconds"`
	Status          string             `db:"status" json:"status"`
	State           string             `db:"state" json:"state"`
	LastCheckedAt   pgtype.Timestamptz `db:"last_checked_at" json:"last_checked_at"`
	NextCheckAt     pgtype.Timestamptz `db:"next_check_at" json:"next_check_at"`
	Settings        json.RawMessage    `db:"settings" json:"settings"`
	CreatedAt       time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time          `db:"updated_at" json:"updated_at"`
	TagsJson        interface{}        `db:"tags_json" json:"tags_json"`
}

func (q *Queries) ListActiveMonitorsDueWithTags(ctx context.Context, limit int32) ([]ListActiveMonitorsDueWithTagsRow, error) {
	rows, err := q.db.Query(ctx, listActiveMonitorsDueWithTags, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveMonitorsDueWithTagsRow{}
	for rows.Next() {
		var i ListActiveMonitorsDueWithTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Target,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.Status,
			&i.State,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TagsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitors = `-- name: ListMonitors :many
SELECT id, name, type, target, interval_seconds, timeout_seconds, status, state, last_checked_at, next_check_at, settings, created_at, updated_at FROM monitors
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListMonitorsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListMonitors(ctx context.Context, arg ListMonitorsParams) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listMonitors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Target,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.Status,
			&i.State,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMonitor = `-- name: UpdateMonitor :one
UPDATE monitors
SET
    name             = $2,
    type             = $3,
    target           = $4,
    interval_seconds = $5,
    timeout_seconds  = $6,
    status           = $7,
    settings         = $8,
    updated_at       = now()
WHERE id = $1
RETURNING id, name, type, target, interval_seconds, timeout_seconds, status, state, last_checked_at, next_check_at, settings, created_at, updated_at
`

type UpdateMonitorParams struct {
	ID              uuid.UUID       `db:"id" json:"id"`
	Name            string          `db:"name" json:"name"`
	Type            string          `db:"type" json:"type"`
	Target          string          `db:"target" json:"target"`
	IntervalSeconds int32           `db:"interval_seconds" json:"interval_seconds"`
	TimeoutSeconds  int32           `db:"timeout_seconds" json:"timeout_seconds"`
	Status          string          `db:"status" json:"status"`
	Settings        json.RawMessage `db:"settings" json:"settings"`
}

func (q *Queries) UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, updateMonitor,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Target,
		arg.IntervalSeconds,
		arg.TimeoutSeconds,
		arg.Status,
		arg.Settings,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Target,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.Status,
		&i.State,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMonitorState = `-- name: UpdateMonitorState :one
UPDATE monitors
SET
    state           = $2,
    last_checked_at = $3,
    next_check_at   = $4,
    updated_at      = now()
WHERE id = $1
RETURNING id, name, type, target, interval_seconds, timeout_seconds, status, state, last_checked_at, next_check_at, settings, created_at, updated_at
`

type UpdateMonitorStateParams struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	State         string             `db:"state" json:"state"`
	LastCheckedAt pgtype.Timestamptz `db:"last_checked_at" json:"last_checked_at"`
	NextCheckAt   pgtype.Timestamptz `db:"next_check_at" json:"next_check_at"`
}

func (q *Queries) UpdateMonitorState(ctx context.Context, arg UpdateMonitorStateParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, updateMonitorState,
		arg.ID,
		arg.State,
		arg.LastCheckedAt,
		arg.NextCheckAt,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Target,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.Status,
		&i.State,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMonitor = `-- name: UpsertMonitor :one
INSERT INTO monitors (
    id, name, type, target, interval_seconds, timeout_seconds,
    status, state, settings, next_check_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, 'unknown', $8, now()
)
ON CONFLICT (id) DO UPDATE SET
    name             = EXCLUDED.name,
    type             = EXCLUDED.type,
    target           = EXCLUDED.target,
    interval_seconds = EXCLUDED.interval_seconds,
    timeout_seconds  = EXCLUDED.timeout_seconds,
    status           = EXCLUDED.status,
    settings         = EXCLUDED.settings,
    updated_at       = now()
RETURNING id, name, type, target, interval_seconds, timeout_seconds, status, state, last_checked_at, next_check_at, settings, created_at, updated_at
`

type UpsertMonitorParams struct {
	ID              uuid.UUID       `db:"id" json:"id"`
	Name            string          `db:"name" json:"name"`
	Type            string          `db:"type" json:"type"`
	Target          string          `db:"target" json:"target"`
	IntervalSeconds int32           `db:"interval_seconds" json:"interval_seconds"`
	TimeoutSeconds  int32           `db:"timeout_seconds" json:"timeout_seconds"`
	Status          string          `db:"status" json:"status"`
	Settings        json.RawMessage `db:"settings" json:"settings"`
}

func (q *Queries) UpsertMonitor(ctx context.Context, arg UpsertMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, upsertMonitor,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Target,
		arg.IntervalSeconds,
		arg.TimeoutSeconds,
		arg.Status,
		arg.Settings,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Target,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.Status,
		&i.State,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
