// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitor_tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countMonitorsFiltered = `-- name: CountMonitorsFiltered :one
SELECT COUNT(*) FROM monitors m
WHERE ($1::text = '' OR m.type = $1)
  AND (
    COALESCE(cardinality($2::text[]), 0) = 0
    OR m.id IN (
      SELECT mt.monitor_id FROM monitor_tags mt
      WHERE (mt.key || ':' || mt.value) = ANY($2::text[])
      GROUP BY mt.monitor_id
      HAVING COUNT(DISTINCT mt.key || ':' || mt.value) = cardinality($2::text[])
    )
  )
`

type CountMonitorsFilteredParams struct {
	Column1 string   `db:"column_1" json:"column_1"`
	Column2 []string `db:"column_2" json:"column_2"`
}

func (q *Queries) CountMonitorsFiltered(ctx context.Context, arg CountMonitorsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMonitorsFiltered, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMonitorTags = `-- name: DeleteMonitorTags :exec
DELETE FROM monitor_tags WHERE monitor_id = $1
`

func (q *Queries) DeleteMonitorTags(ctx context.Context, monitorID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMonitorTags, monitorID)
	return err
}

const insertMonitorTag = `-- name: InsertMonitorTag :exec
INSERT INTO monitor_tags (monitor_id, key, value)
VALUES ($1, $2, $3)
`

type InsertMonitorTagParams struct {
	MonitorID uuid.UUID `db:"monitor_id" json:"monitor_id"`
	Key       string    `db:"key" json:"key"`
	Value     string    `db:"value" json:"value"`
}

func (q *Queries) InsertMonitorTag(ctx context.Context, arg InsertMonitorTagParams) error {
	_, err := q.db.Exec(ctx, insertMonitorTag, arg.MonitorID, arg.Key, arg.Value)
	return err
}

const listAllTagKeys = `-- name: ListAllTagKeys :many
SELECT DISTINCT key FROM monitor_tags
ORDER BY key
`

func (q *Queries) ListAllTagKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAllTagKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitorsFiltered = `-- name: ListMonitorsFiltered :many
SELECT m.id, m.name, m.type, m.target, m.interval_seconds, m.timeout_seconds, m.status, m.state, m.last_checked_at, m.next_check_at, m.settings, m.created_at, m.updated_at, m.history_retention_days FROM monitors m
WHERE ($1::text = '' OR m.type = $1)
  AND (
    COALESCE(cardinality($2::text[]), 0) = 0
    OR m.id IN (
      SELECT mt.monitor_id FROM monitor_tags mt
      WHERE (mt.key || ':' || mt.value) = ANY($2::text[])
      Group BY mt.monitor_id
      HAVING COUNT(DISTINCT mt.key || ':' || mt.value) = cardinality($2::text[])
    )
  )
ORDER BY m.created_at DESC
LIMIT $3 OFFSET $4
`

type ListMonitorsFilteredParams struct {
	Column1 string   `db:"column_1" json:"column_1"`
	Column2 []string `db:"column_2" json:"column_2"`
	Limit   int32    `db:"limit" json:"limit"`
	Offset  int32    `db:"offset" json:"offset"`
}

func (q *Queries) ListMonitorsFiltered(ctx context.Context, arg ListMonitorsFilteredParams) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listMonitorsFiltered,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Target,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.Status,
			&i.State,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HistoryRetentionDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagValues = `-- name: ListTagValues :many
SELECT DISTINCT value FROM monitor_tags
WHERE key = $1
ORDER BY value
`

func (q *Queries) ListTagValues(ctx context.Context, key string) ([]string, error) {
	rows, err := q.db.Query(ctx, listTagValues, key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var value string
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByMonitor = `-- name: ListTagsByMonitor :many
SELECT id, monitor_id, key, value FROM monitor_tags
WHERE monitor_id = $1
ORDER BY key, value
`

func (q *Queries) ListTagsByMonitor(ctx context.Context, monitorID uuid.UUID) ([]MonitorTag, error) {
	rows, err := q.db.Query(ctx, listTagsByMonitor, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitorTag{}
	for rows.Next() {
		var i MonitorTag
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.Key,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
