// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_channels.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countBindingsByMonitor = `-- name: CountBindingsByMonitor :one
SELECT COUNT(*) FROM channel_bindings
WHERE monitor_id = $1
`

func (q *Queries) CountBindingsByMonitor(ctx context.Context, monitorID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBindingsByMonitor, monitorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChannels = `-- name: CountChannels :one
SELECT COUNT(*) FROM notification_channels
`

func (q *Queries) CountChannels(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countChannels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDeliveryLogsByChannel = `-- name: CountDeliveryLogsByChannel :one
SELECT COUNT(*) FROM delivery_logs
WHERE channel_id = $1
`

func (q *Queries) CountDeliveryLogsByChannel(ctx context.Context, channelID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDeliveryLogsByChannel, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDeliveryLogsByMonitor = `-- name: CountDeliveryLogsByMonitor :one
SELECT COUNT(*) FROM delivery_logs
WHERE monitor_id = $1
`

func (q *Queries) CountDeliveryLogsByMonitor(ctx context.Context, monitorID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDeliveryLogsByMonitor, monitorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBinding = `-- name: CreateBinding :one
INSERT INTO channel_bindings (channel_id, monitor_id, triggers, reminder_interval_minutes)
VALUES ($1, $2, $3, $4)
RETURNING id, channel_id, monitor_id, triggers, reminder_interval_minutes, created_at, updated_at
`

type CreateBindingParams struct {
	ChannelID               uuid.UUID       `db:"channel_id" json:"channel_id"`
	MonitorID               uuid.UUID       `db:"monitor_id" json:"monitor_id"`
	Triggers                json.RawMessage `db:"triggers" json:"triggers"`
	ReminderIntervalMinutes *int32          `db:"reminder_interval_minutes" json:"reminder_interval_minutes"`
}

func (q *Queries) CreateBinding(ctx context.Context, arg CreateBindingParams) (ChannelBinding, error) {
	row := q.db.QueryRow(ctx, createBinding,
		arg.ChannelID,
		arg.MonitorID,
		arg.Triggers,
		arg.ReminderIntervalMinutes,
	)
	var i ChannelBinding
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.MonitorID,
		&i.Triggers,
		&i.ReminderIntervalMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO notification_channels (name, channel_type, config)
VALUES ($1, $2, $3)
RETURNING id, name, channel_type, config, created_at, updated_at
`

type CreateChannelParams struct {
	Name        string          `db:"name" json:"name"`
	ChannelType string          `db:"channel_type" json:"channel_type"`
	Config      json.RawMessage `db:"config" json:"config"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, createChannel, arg.Name, arg.ChannelType, arg.Config)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ChannelType,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBinding = `-- name: DeleteBinding :exec
DELETE FROM channel_bindings WHERE id = $1
`

func (q *Queries) DeleteBinding(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBinding, id)
	return err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM notification_channels WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChannel, id)
	return err
}

const deleteSMTPSettings = `-- name: DeleteSMTPSettings :exec
DELETE FROM smtp_settings
`

func (q *Queries) DeleteSMTPSettings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteSMTPSettings)
	return err
}

const getBinding = `-- name: GetBinding :one
SELECT id, channel_id, monitor_id, triggers, reminder_interval_minutes, created_at, updated_at FROM channel_bindings
WHERE id = $1
`

func (q *Queries) GetBinding(ctx context.Context, id uuid.UUID) (ChannelBinding, error) {
	row := q.db.QueryRow(ctx, getBinding, id)
	var i ChannelBinding
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.MonitorID,
		&i.Triggers,
		&i.ReminderIntervalMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannel = `-- name: GetChannel :one
SELECT id, name, channel_type, config, created_at, updated_at FROM notification_channels
WHERE id = $1
`

func (q *Queries) GetChannel(ctx context.Context, id uuid.UUID) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ChannelType,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSMTPSettings = `-- name: GetSMTPSettings :one
SELECT id, host, port, username, password_enc, from_address, tls_enabled, created_at, updated_at FROM smtp_settings
LIMIT 1
`

func (q *Queries) GetSMTPSettings(ctx context.Context) (SmtpSetting, error) {
	row := q.db.QueryRow(ctx, getSMTPSettings)
	var i SmtpSetting
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEnc,
		&i.FromAddress,
		&i.TlsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDeliveryLog = `-- name: InsertDeliveryLog :one
INSERT INTO delivery_logs (channel_id, monitor_id, binding_id, trigger_type, attempt, status, error_detail)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, channel_id, monitor_id, binding_id, trigger_type, attempt, status, error_detail, created_at
`

type InsertDeliveryLogParams struct {
	ChannelID   uuid.UUID   `db:"channel_id" json:"channel_id"`
	MonitorID   uuid.UUID   `db:"monitor_id" json:"monitor_id"`
	BindingID   pgtype.UUID `db:"binding_id" json:"binding_id"`
	TriggerType string      `db:"trigger_type" json:"trigger_type"`
	Attempt     int32       `db:"attempt" json:"attempt"`
	Status      string      `db:"status" json:"status"`
	ErrorDetail *string     `db:"error_detail" json:"error_detail"`
}

func (q *Queries) InsertDeliveryLog(ctx context.Context, arg InsertDeliveryLogParams) (DeliveryLog, error) {
	row := q.db.QueryRow(ctx, insertDeliveryLog,
		arg.ChannelID,
		arg.MonitorID,
		arg.BindingID,
		arg.TriggerType,
		arg.Attempt,
		arg.Status,
		arg.ErrorDetail,
	)
	var i DeliveryLog
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.MonitorID,
		&i.BindingID,
		&i.TriggerType,
		&i.Attempt,
		&i.Status,
		&i.ErrorDetail,
		&i.CreatedAt,
	)
	return i, err
}

const listBindingsByChannel = `-- name: ListBindingsByChannel :many
SELECT id, channel_id, monitor_id, triggers, reminder_interval_minutes, created_at, updated_at FROM channel_bindings
WHERE channel_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBindingsByChannel(ctx context.Context, channelID uuid.UUID) ([]ChannelBinding, error) {
	rows, err := q.db.Query(ctx, listBindingsByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelBinding{}
	for rows.Next() {
		var i ChannelBinding
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.MonitorID,
			&i.Triggers,
			&i.ReminderIntervalMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBindingsByMonitor = `-- name: ListBindingsByMonitor :many
SELECT id, channel_id, monitor_id, triggers, reminder_interval_minutes, created_at, updated_at FROM channel_bindings
WHERE monitor_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBindingsByMonitor(ctx context.Context, monitorID uuid.UUID) ([]ChannelBinding, error) {
	rows, err := q.db.Query(ctx, listBindingsByMonitor, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelBinding{}
	for rows.Next() {
		var i ChannelBinding
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.MonitorID,
			&i.Triggers,
			&i.ReminderIntervalMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBindingsByMonitorPaginated = `-- name: ListBindingsByMonitorPaginated :many
SELECT id, channel_id, monitor_id, triggers, reminder_interval_minutes, created_at, updated_at FROM channel_bindings
WHERE monitor_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBindingsByMonitorPaginatedParams struct {
	MonitorID uuid.UUID `db:"monitor_id" json:"monitor_id"`
	Limit     int32     `db:"limit" json:"limit"`
	Offset    int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListBindingsByMonitorPaginated(ctx context.Context, arg ListBindingsByMonitorPaginatedParams) ([]ChannelBinding, error) {
	rows, err := q.db.Query(ctx, listBindingsByMonitorPaginated, arg.MonitorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelBinding{}
	for rows.Next() {
		var i ChannelBinding
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.MonitorID,
			&i.Triggers,
			&i.ReminderIntervalMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannels = `-- name: ListChannels :many
SELECT id, name, channel_type, config, created_at, updated_at FROM notification_channels
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListChannelsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListChannels(ctx context.Context, arg ListChannelsParams) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listChannels, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ChannelType,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveryLogsByChannel = `-- name: ListDeliveryLogsByChannel :many
SELECT id, channel_id, monitor_id, binding_id, trigger_type, attempt, status, error_detail, created_at FROM delivery_logs
WHERE channel_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDeliveryLogsByChannelParams struct {
	ChannelID uuid.UUID `db:"channel_id" json:"channel_id"`
	Limit     int32     `db:"limit" json:"limit"`
	Offset    int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListDeliveryLogsByChannel(ctx context.Context, arg ListDeliveryLogsByChannelParams) ([]DeliveryLog, error) {
	rows, err := q.db.Query(ctx, listDeliveryLogsByChannel, arg.ChannelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryLog{}
	for rows.Next() {
		var i DeliveryLog
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.MonitorID,
			&i.BindingID,
			&i.TriggerType,
			&i.Attempt,
			&i.Status,
			&i.ErrorDetail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveryLogsByMonitor = `-- name: ListDeliveryLogsByMonitor :many
SELECT id, channel_id, monitor_id, binding_id, trigger_type, attempt, status, error_detail, created_at FROM delivery_logs
WHERE monitor_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDeliveryLogsByMonitorParams struct {
	MonitorID uuid.UUID `db:"monitor_id" json:"monitor_id"`
	Limit     int32     `db:"limit" json:"limit"`
	Offset    int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListDeliveryLogsByMonitor(ctx context.Context, arg ListDeliveryLogsByMonitorParams) ([]DeliveryLog, error) {
	rows, err := q.db.Query(ctx, listDeliveryLogsByMonitor, arg.MonitorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryLog{}
	for rows.Next() {
		var i DeliveryLog
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.MonitorID,
			&i.BindingID,
			&i.TriggerType,
			&i.Attempt,
			&i.Status,
			&i.ErrorDetail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBinding = `-- name: UpdateBinding :one
UPDATE channel_bindings
SET
    triggers                  = $2,
    reminder_interval_minutes = $3,
    updated_at                = now()
WHERE id = $1
RETURNING id, channel_id, monitor_id, triggers, reminder_interval_minutes, created_at, updated_at
`

type UpdateBindingParams struct {
	ID                      uuid.UUID       `db:"id" json:"id"`
	Triggers                json.RawMessage `db:"triggers" json:"triggers"`
	ReminderIntervalMinutes *int32          `db:"reminder_interval_minutes" json:"reminder_interval_minutes"`
}

func (q *Queries) UpdateBinding(ctx context.Context, arg UpdateBindingParams) (ChannelBinding, error) {
	row := q.db.QueryRow(ctx, updateBinding, arg.ID, arg.Triggers, arg.ReminderIntervalMinutes)
	var i ChannelBinding
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.MonitorID,
		&i.Triggers,
		&i.ReminderIntervalMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE notification_channels
SET
    name         = $2,
    channel_type = $3,
    config       = $4,
    updated_at   = now()
WHERE id = $1
RETURNING id, name, channel_type, config, created_at, updated_at
`

type UpdateChannelParams struct {
	ID          uuid.UUID       `db:"id" json:"id"`
	Name        string          `db:"name" json:"name"`
	ChannelType string          `db:"channel_type" json:"channel_type"`
	Config      json.RawMessage `db:"config" json:"config"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.ID,
		arg.Name,
		arg.ChannelType,
		arg.Config,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ChannelType,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSMTPSettings = `-- name: UpsertSMTPSettings :one
INSERT INTO smtp_settings (id, host, port, username, password_enc, from_address, tls_enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    host         = EXCLUDED.host,
    port         = EXCLUDED.port,
    username     = EXCLUDED.username,
    password_enc = EXCLUDED.password_enc,
    from_address = EXCLUDED.from_address,
    tls_enabled  = EXCLUDED.tls_enabled,
    updated_at   = now()
RETURNING id, host, port, username, password_enc, from_address, tls_enabled, created_at, updated_at
`

type UpsertSMTPSettingsParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Host        string    `db:"host" json:"host"`
	Port        int32     `db:"port" json:"port"`
	Username    *string   `db:"username" json:"username"`
	PasswordEnc []byte    `db:"password_enc" json:"password_enc"`
	FromAddress string    `db:"from_address" json:"from_address"`
	TlsEnabled  bool      `db:"tls_enabled" json:"tls_enabled"`
}

func (q *Queries) UpsertSMTPSettings(ctx context.Context, arg UpsertSMTPSettingsParams) (SmtpSetting, error) {
	row := q.db.QueryRow(ctx, upsertSMTPSettings,
		arg.ID,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.PasswordEnc,
		arg.FromAddress,
		arg.TlsEnabled,
	)
	var i SmtpSetting
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEnc,
		&i.FromAddress,
		&i.TlsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
