// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proto_sources.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const deleteProtoSource = `-- name: DeleteProtoSource :exec
DELETE FROM proto_sources WHERE monitor_id = $1
`

func (q *Queries) DeleteProtoSource(ctx context.Context, monitorID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProtoSource, monitorID)
	return err
}

const getProtoSource = `-- name: GetProtoSource :one
SELECT id, monitor_id, source_type, descriptor_bytes, metadata, created_at, updated_at FROM proto_sources WHERE monitor_id = $1
`

func (q *Queries) GetProtoSource(ctx context.Context, monitorID uuid.UUID) (ProtoSource, error) {
	row := q.db.QueryRow(ctx, getProtoSource, monitorID)
	var i ProtoSource
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.SourceType,
		&i.DescriptorBytes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const protoSourceExists = `-- name: ProtoSourceExists :one
SELECT EXISTS(SELECT 1 FROM proto_sources WHERE monitor_id = $1)
`

func (q *Queries) ProtoSourceExists(ctx context.Context, monitorID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, protoSourceExists, monitorID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertProtoSource = `-- name: UpsertProtoSource :one
INSERT INTO proto_sources (monitor_id, source_type, descriptor_bytes, metadata, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (monitor_id) DO UPDATE SET
    source_type = EXCLUDED.source_type,
    descriptor_bytes = EXCLUDED.descriptor_bytes,
    metadata = EXCLUDED.metadata,
    updated_at = now()
RETURNING id, monitor_id, source_type, descriptor_bytes, metadata, created_at, updated_at
`

type UpsertProtoSourceParams struct {
	MonitorID       uuid.UUID       `db:"monitor_id" json:"monitor_id"`
	SourceType      string          `db:"source_type" json:"source_type"`
	DescriptorBytes []byte          `db:"descriptor_bytes" json:"descriptor_bytes"`
	Metadata        json.RawMessage `db:"metadata" json:"metadata"`
}

func (q *Queries) UpsertProtoSource(ctx context.Context, arg UpsertProtoSourceParams) (ProtoSource, error) {
	row := q.db.QueryRow(ctx, upsertProtoSource,
		arg.MonitorID,
		arg.SourceType,
		arg.DescriptorBytes,
		arg.Metadata,
	)
	var i ProtoSource
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.SourceType,
		&i.DescriptorBytes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
