// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSecrets = `-- name: CountSecrets :one
SELECT COUNT(*) FROM secrets
`

func (q *Queries) CountSecrets(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSecrets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSecret = `-- name: CreateSecret :one
INSERT INTO secrets (name, encrypted_value)
VALUES ($1, $2)
RETURNING id, name, encrypted_value, created_at, updated_at
`

type CreateSecretParams struct {
	Name           string `db:"name" json:"name"`
	EncryptedValue string `db:"encrypted_value" json:"encrypted_value"`
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, createSecret, arg.Name, arg.EncryptedValue)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EncryptedValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM secrets WHERE id = $1
`

func (q *Queries) DeleteSecret(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSecret, id)
	return err
}

const getSecret = `-- name: GetSecret :one
SELECT id, name, encrypted_value, created_at, updated_at FROM secrets WHERE id = $1
`

func (q *Queries) GetSecret(ctx context.Context, id uuid.UUID) (Secret, error) {
	row := q.db.QueryRow(ctx, getSecret, id)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EncryptedValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecrets = `-- name: ListSecrets :many
SELECT id, name, created_at, updated_at FROM secrets
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSecretsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListSecretsRow struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListSecrets(ctx context.Context, arg ListSecretsParams) ([]ListSecretsRow, error) {
	rows, err := q.db.Query(ctx, listSecrets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretsRow{}
	for rows.Next() {
		var i ListSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecret = `-- name: UpdateSecret :one
UPDATE secrets
SET
    name            = $2,
    encrypted_value = $3,
    updated_at      = now()
WHERE id = $1
RETURNING id, name, encrypted_value, created_at, updated_at
`

type UpdateSecretParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	Name           string    `db:"name" json:"name"`
	EncryptedValue string    `db:"encrypted_value" json:"encrypted_value"`
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, updateSecret, arg.ID, arg.Name, arg.EncryptedValue)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EncryptedValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
